import "./globals.css";
// import localFont from 'next/font/local'

// // Font files can be colocated inside of `pages`
// const myFont = localFont({ src: './Qelthan.otf' })

import { Azeret_Mono, DM_Sans } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const font = DM_Sans(
  { subsets: ["latin"] },
  {
    weight: ["400", "500", "600", "700", "800", "900"],
  }
);

const font2 = Azeret_Mono(
  { subsets: ["latin"] },
  {
    weight: ["400", "500", "600", "700", "800", "900"],
  }
);

export const metadata = {
  title: "Home Remodeling Web Design Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
